//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 11:45:56 AM EDT 
//


package ca.drugbank.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calculated-property-source-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="calculated-property-source-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ChemAxon"/>
 *     &lt;enumeration value="ALOGPS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "calculated-property-source-type")
@XmlEnum
public enum CalculatedPropertySourceType {

    @XmlEnumValue("ChemAxon")
    CHEM_AXON("ChemAxon"),
    ALOGPS("ALOGPS");
    private final String value;

    CalculatedPropertySourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CalculatedPropertySourceType fromValue(String v) {
        for (CalculatedPropertySourceType c: CalculatedPropertySourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
