//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 11:45:56 AM EDT 
//


package ca.drugbank.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for external-link-resource-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="external-link-resource-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RxList"/>
 *     &lt;enumeration value="PDRhealth"/>
 *     &lt;enumeration value="Drugs.com"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "external-link-resource-type")
@XmlEnum
public enum ExternalLinkResourceType {

    @XmlEnumValue("RxList")
    RX_LIST("RxList"),
    @XmlEnumValue("PDRhealth")
    PD_RHEALTH("PDRhealth"),
    @XmlEnumValue("Drugs.com")
    DRUGS_COM("Drugs.com");
    private final String value;

    ExternalLinkResourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExternalLinkResourceType fromValue(String v) {
        for (ExternalLinkResourceType c: ExternalLinkResourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
