//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:04:57 PM EST 
//


package ca.drugbank.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reference-list-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reference-list-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="articles" type="{http://www.drugbank.ca}article-list-type"/>
 *         &lt;element name="textbooks" type="{http://www.drugbank.ca}textbook-list-type"/>
 *         &lt;element name="links" type="{http://www.drugbank.ca}link-list-type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reference-list-type", propOrder = {
    "articles",
    "textbooks",
    "links"
})
public class ReferenceListType {

    @XmlElement(required = true)
    protected ArticleListType articles;
    @XmlElement(required = true)
    protected TextbookListType textbooks;
    @XmlElement(required = true)
    protected LinkListType links;

    /**
     * Gets the value of the articles property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleListType }
     *     
     */
    public ArticleListType getArticles() {
        return articles;
    }

    /**
     * Sets the value of the articles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleListType }
     *     
     */
    public void setArticles(ArticleListType value) {
        this.articles = value;
    }

    /**
     * Gets the value of the textbooks property.
     * 
     * @return
     *     possible object is
     *     {@link TextbookListType }
     *     
     */
    public TextbookListType getTextbooks() {
        return textbooks;
    }

    /**
     * Sets the value of the textbooks property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextbookListType }
     *     
     */
    public void setTextbooks(TextbookListType value) {
        this.textbooks = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link LinkListType }
     *     
     */
    public LinkListType getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkListType }
     *     
     */
    public void setLinks(LinkListType value) {
        this.links = value;
    }

}
